<a href="https://colab.research.google.com/github/seomj0914/MyStudy/blob/main/(%EB%B2%88%EC%99%B8)%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D%EC%9D%98_%ED%99%9C%EC%9A%A9_%EB%AF%B8%EC%99%84%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(['Mouse','dog','house and parrot','23'],columns=['values'])
df

             values
0             Mouse
1               dog
2  house and parrot
3                23

In [ ]:
df['v1'] = df['values'].str.contains('dog')
df

             values     v1
0             Mouse  False
1               dog   True
2  house and parrot  False
3                23  False

In [ ]:
df['v2'] = df['values'].str.contains('og',regex=False)
df

             values     v1     v2
0             Mouse  False  False
1               dog   True   True
2  house and parrot  False  False
3                23  False  False

In [ ]:
#case=True는 대소문자 구분지어 판별
df['v3'] = df['values'].str.contains('oG',regex=False,case=True)
df

             values     v1     v2     v3
0             Mouse  False  False  False
1               dog   True   True  False
2  house and parrot  False  False  False
3                23  False  False  False

In [ ]:
#'/d' 는 숫자 
# regex=True 는 즉 '/' 뒤가 regular express 이다.
# regex=False 는 즉 '/' 뒤가 regular express 이 아니다. 일반 string 이다.
df['v4'] = df['values'].str.contains('\d',regex=True)
df['v5'] = df['values'].str.contains('\d',regex=False)

In [ ]:
df2 = pd.DataFrame(['40','40.0','41','41.0','35'],columns=['values'])
df2

  values
0     40
1   40.0
2     41
3   41.0
4     35

In [ ]:
df2['v1-1'] = df2['values'].str.contains('.0',regex=True)
df2['v2-2'] = df2['values'].str.contains('\.0',regex=False)
df2['v2'] = df2['values'].str.contains('.0',regex=False)
df2

  values   v1-1   v2-2     v2
0     40   True  False  False
1   40.0   True  False   True
2     41  False  False  False
3   41.0   True  False   True
4     35  False  False  False

In [ ]:
df3 = pd.DataFrame(['a1','b2','c3'],columns=['values'])
df3

  values
0     a1
1     b2
2     c3

In [ ]:
df3['values'].str.extract('[ab]\d')

ValueError: ignored